/**
 * Project: MicroSnap Builder
 * Description: Handles the dynamic rendering of slides , manages playback controls, animation triggers, and slide navigation.
 * Author: Dominique Thomas (github.com/dominique-thomas)
 * License: Shared publicly for demonstration purposes only. Reuse or redistribution not permitted without permission.
 */
window.previewScript = `let slidesContainer=document.getElementById("slides");let slides=document.querySelectorAll(".slide");let counter=document.getElementById("slideCounter");let progressBar=document.getElementById("progressBar");let deck=document.querySelector(".deck-container");let navArrows=document.querySelector(".nav-arrows");let isTransitioning=!1;let arrowTimeout;let current=0;let autoplay=!1;let autoplayInterval;let loop=!1;let startX=0;let endX=0;let isSingleSlide=!1;let duration=6000;const swipeThreshold=40;function showArrows(){clearTimeout(arrowTimeout);navArrows.style.opacity="1";arrowTimeout=setTimeout(()=>{navArrows.style.opacity="0"},1500)}
function animateProgress(){progressBar.style.transition="none";progressBar.style.width="0%";void progressBar.offsetWidth;progressBar.style.transition="width "+duration+"ms linear";progressBar.style.width="100%"}
function showSlide(index){current=(index+slides.length)%slides.length;slidesContainer.style.transform="translateX(-"+(current*100)+"%)";counter.textContent=(current+1)+"/"+slides.length;animateProgress()}
function nextSlide(fromAuto=!1){if(isTransitioning)return;isTransitioning=!0;if(fromAuto&&!loop&&current===slides.length-1){isTransitioning=!1;return}
if(!fromAuto&&current===slides.length-1){current=0}else{current++}
showSlide(current);replayTextAnimation(slides[current]);setTimeout(()=>(isTransitioning=!1),600)}
function prevSlide(fromAuto=!1){if(isTransitioning)return;isTransitioning=!0;if(fromAuto&&!loop&&current===0){isTransitioning=!1;return}
if(!fromAuto&&current===0){current=slides.length-1}else{current--}
showSlide(current);replayTextAnimation(slides[current]);setTimeout(()=>(isTransitioning=!1),600)}
function resetDeck(){current=0;showSlide(current);replayTextAnimation(slides[current]);isTransitioning=!1}
document.getElementById("nextSlide").addEventListener("click",()=>{nextSlide();if(autoplay)
restartAutoplay();});document.getElementById("prevSlide").addEventListener("click",()=>{prevSlide();if(autoplay)
restartAutoplay();});function startAutoplay(){clearInterval(autoplayInterval);if(!autoplay)return;animateProgress();autoplayInterval=setInterval(()=>{nextSlide(!0)},duration)}
function stopAutoplay(){clearInterval(autoplayInterval)}
function restartAutoplay(){stopAutoplay();startAutoplay()}
deck.addEventListener("mousemove",showArrows);deck.addEventListener("touchstart",showArrows);deck.addEventListener("touchstart",e=>{startX=e.changedTouches[0].screenX});deck.addEventListener("touchend",e=>{endX=e.changedTouches[0].screenX;handleSwipe()});deck.addEventListener("mousedown",e=>{startX=e.clientX});deck.addEventListener("mouseup",e=>{endX=e.clientX;handleSwipe()});function handleSwipe(){if(isSingleSlide)return;const diff=endX-startX;if(Math.abs(diff)<swipeThreshold)return;progressBar.style.transition="none";progressBar.style.width="0%";if(autoplay)restartAutoplay();if(diff>0){prevSlide()}else{nextSlide()}}
function replayTextAnimation(slide){const animEls=slide.querySelectorAll("[class*='fade']");if(!animEls.length)return;animEls.forEach(el=>{const fadeClass=Array.from(el.classList).find(c=>c.startsWith("fade"));if(!fadeClass)return;el.classList.remove(fadeClass);el.style.opacity="0";void el.offsetWidth;setTimeout(()=>{el.classList.add(fadeClass);el.style.opacity="";el.style.animationDelay="0s"},500)})}
function hexToRgba(hex,alpha=0.45){if(!hex||typeof hex!=="string")return hex;hex=hex.trim();hex=hex.replace(/;/g,"");hex=hex.replace(/^#?([a-f0-9])([a-f0-9])([a-f0-9])$/i,(m,r,g,b)=>"#"+r+r+g+g+b+b);const result=/^#?([a-f0-9]{2})([a-f0-9]{2})([a-f0-9]{2})$/i.exec(hex);return result?"rgba("+parseInt(result[1],16)+", "+parseInt(result[2],16)+", "+parseInt(result[3],16)+", "+alpha+")":hex}
function renderDeck(deckData,mode="deck"){slidesContainer=document.getElementById("slides");slidesContainer.innerHTML="";autoplay=deckData.autoplay;loop=deckData.loop;if(deckData.slides.length===1){isSingleSlide=!0}else{isSingleSlide=!1}
if(deckData.slides.length>5){deckData.slides=deckData.slides.slice(0,5);console.warn("Only the first 5 slides will be shown (max limit reached).")}
deckData.slides.forEach(slide=>{const slideDiv=document.createElement("div");slideDiv.className="slide "+(slide.layout||"");const textDiv=document.createElement("div");textDiv.className="slide-text text-"+(slide.position||"center")+" font-"+(slide.fontSize||"medium");textDiv.innerHTML="<h2 class='textAnim "+slide.animation+"'>"+(slide.title||"")+"</h2><p class='textAnim "+slide.animation+"'>"+(slide.description||"")+"</p>";if(slide.layout==="layout-split"&&slide.image){const img=document.createElement("img");img.src=slide.image;img.alt=slide.alt||"";slideDiv.appendChild(img);textDiv.style.background=slide.background||"#0a9c97"}else if(slide.background){const bg=slide.background.trim();if(slide.image){slideDiv.style.background="url('"+slide.image+"') center/cover no-repeat"}else if(bg.includes("http")||bg.startsWith("url(")){slideDiv.style.background=bg.startsWith("url(")?bg:"url('"+bg+"') center/cover no-repeat"}else{slideDiv.style.background=bg}
if(slide.layout==="layout-overlay"&&slide.image){const overlay=document.createElement("div");overlay.className="slide-overlay";overlay.style.position="absolute";overlay.style.inset=0;overlay.style.background=hexToRgba(slide.background);slideDiv.appendChild(overlay)}}
slideDiv.appendChild(textDiv);slidesContainer.appendChild(slideDiv)});if(mode==="export"){slidesContainer=document.getElementById("slides");slides=document.querySelectorAll(".slide");counter=document.getElementById("slideCounter");progressBar=document.getElementById("progressBar");deck=document.querySelector(".deck-container");navArrows=document.querySelector(".nav-arrows");navArrows.style.opacity="1";if(isSingleSlide){autoplay=!1;navArrows.style.display="none";progressBar.style.display="none";navArrows.style.opacity="0"}else{progressBar.style.display="";navArrows.style.display=""}
counter.textContent=(current+1)+" / "+slides.length;resetDeck();startAutoplay()}}`;